import fs from 'node:fs'
import path from 'node:path'

// Generate src/version.ts from package.json so the running relay can report
// its own version (e.g. in GET /health) without reading package.json at
// runtime — the built code runs from dist/ where the package layout is not
// guaranteed. Regenerated on every build; committed so the source tree is
// self-consistent between builds.
const pkgPath = path.resolve('package.json')
const outPath = path.resolve('src', 'version.ts')

const { version } = JSON.parse(fs.readFileSync(pkgPath, 'utf8'))
const contents = `// Generated by scripts/write-version.mjs — do not edit by hand.
export const RELAY_VERSION = '${version}'
`

const existing = fs.existsSync(outPath) ? fs.readFileSync(outPath, 'utf8') : ''
if (existing !== contents) {
  fs.writeFileSync(outPath, contents, 'utf8')
}
